trigger:
- master

pool:
  name: 'fyp_pool'

steps:
- script: echo Hello World!
  displayName: 'Run a one-liner script'
- checkout: self
  fetchDepth: 0

- script: |
    echo This codespace hostname:
    echo ------------------------
    echo $HOSTNAME
  displayName: 'Run a multi-line script'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'fyp-sonar-key'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '21025478_mvc2'
    cliProjectName: 'mvc2'
    cliSources: '.'
- task: SonarCloudAnalyze@1

- task: Bash@3
  displayName: 'Run Codecov'
  inputs:
    targetType: 'inline'
    script: |
      bash <(curl -s https://codecov.io/bash) -t <dbb87a58-02a5-4c7d-a16e-7cb887cec075>

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'