trigger:
- master

pool:
  name: 'fyp_pool'

steps:
- script: echo Hello World!
  displayName: 'Run a one-liner script'

- script: |
    echo This codespace hostname:
    echo ------------------------
    echo $HOSTNAME
  displayName: 'Run a multi-line script'
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: '$(projectName)'